### ISSUE TITLE
Cannot authenticate to humblebundle

### ISSUE THREAD

**Issue by Ram-Z** [MestreLion/humblebundle#28]
I believe Humblebundle may have changed their auth method. Can someone reproduce this?

```
❱❱ ./humblebundle.py --username "<username>" --password "<password>" -Dv
2017-01-15 18:23:14,872	INFO    	Saving credentials
2017-01-15 18:23:14,873	INFO    	Retrieving keys from 'https://www.humblebundle.com/home/keys'
2017-01-15 18:23:15,366	INFO    	Authenticating at 'https://www.humblebundle.com/processlogin'
2017-01-15 18:23:15,629	CRITICAL	HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "./humblebundle.py", line 1018, in cli
    sys.exit(main())
  File "./humblebundle.py", line 728, in main
    debug=args.debug)
  File "./humblebundle.py", line 154, in __init__
    self.update()
  File "./humblebundle.py", line 188, in update
    self.get('/home/keys').read(), re.MULTILINE)
  File "./humblebundle.py", line 694, in get
    '_le_csrf_token': token})
  File "/home/ramsi/src/humblebundle/httpbot.py", line 63, in get
    return self._opener.open(url, urllib.urlencode(postdata))
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized
```

**Comment by MestreLion** [comment]
Hopefully this will fix your issue. I was able to authenticate and download games after that. Just a few notes:

- Using `-Dv` means `debug` *and* `verbose`, which are mutually exclusive, verbose takes precedence in this case.
- You need to specify an "action" in the command line, so add at least a `-u|--update` somewhere. It could be `-Du` or `-vu`
- Before trying to authenticate again, clear all authentication-related data, just in case: `humblebundle -C`
- Authenticate with `--username` and `--password`. It will most likely ask about an email verification code.
- Run again with the code only (username and password are stored from first usage), so `humblebundle --code '<code>' -Du`

Hope this helps!

**Comment by Ram-Z** [comment]
It works. Thanks.

Sorry for the late reply. For some reason I did not get a notification. :confused:
