### ISSUE TITLE
How to download on Windows

### ISSUE THREAD

**Issue by tobias-p** [MestreLion/humblebundle#41]
Hi there, tried to use your app, but always get the following error

`Traceback (most recent call last):
  File "D:\Dev\Downloader\HB\humblebundle.py", line 51, in <module>
    import xdg.BaseDirectory as xdg
  File "d:\dev\Python2.7.14\lib\site-packages\xdg.py", line 18
SyntaxError: Non-ASCII character '\xc2' in file d:\dev\Python2.7.14\lib\site-packages\xdg.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

could you probably help me?

**Comment by tobias-p** [comment]
No help for me?

**Comment by MestreLion** [comment]
This looks like an error in `xdg` module. Where and how did you download it? Please note that on PyPI the correct project is `pyxdg` **not** `xdg`
